events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    upstream frontend {
        server cvailor-frontend:3000;
    }

    upstream backend {
        server cvailor-api:8000;
    }

    server {
        listen 80;
        server_name 35.179.135.94;

        location / {
            proxy_pass http://frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /api/auth {
            proxy_pass http://frontend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

	location /api/v1/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /docs {
            proxy_pass http://backend;
            proxy_set_header Host $host;
        }
    }
}
